---

image: python:3.9

pipelines:
  default:
    - step:
        name: build all
        caches:
          - pip
        script:
          - uname -a
          - apt-get update && apt-get install -y make python3-yaml ctags
          - python --version
          - pip --version
          - pip install -U -r requirements.txt
          - pip freeze
          - make help
          - make clean all
          - make run
        artifacts:
          - target/dist/**
          - target/docs/html/**
