image: python:3.7.3

pipelines:
  default:
    - step:
        name: build all
        caches:
          - pip
        script:
          - uname -a
          - apt-get update && apt-get install -y make python3-yaml
          - python --version
          - pip --version
          - pip install -r requirements.txt
          - pip freeze
          - make help
          - make clean all
        artifacts:
          - target/dist/**
          - target/docs/html/**
