---

image: python:3.9

pipelines:
  default:
    - step:
        name: build all
        caches:
          - pip
        script:
          - uname -a
          - apt-get update && apt-get install -y make python3-yaml ctags
          - python --version
          - pip --version
          - pip install -Ur requirements.txt
          - make clean all
        artifacts:
          - target/dist/**
          - target/docs/html/**
