---

name: Python application

on:
  push:
    branches:
      - master
      - 'feature/*'
  schedule:
    - cron: '0 0 * * *'  # daily

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: set up python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: install dependencies
        run: |
          python -V
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -U -r requirements.txt
          echo isort $(isort --version-number)
          black --version
          flake8 --version
          pylint --version

      - name: check source
        run: |
          isort --check --diff main.py employees/*.py utils/*.py tests/*.py
          black --check main.py employees/*.py utils/*.py tests/*.py
          pylint main.py employees/*.py utils/*.py tests/*.py
          python setup.py check

      - name: test
        run: |
          pytest -v --cov-report term-missing --cov=employees tests/

      - name: run example application
        run: |
          python -m main -h
          python -m main --version
          python -m main -v tests/test.yaml

      - name: make documentation
        run: |
          pytest -v --html=cover/report.html --cov=employees tests/
          coverage html -d cover employees/employees.py
          (cd docs; make html)

      - name: publish to pages
        uses: crazy-max/ghaction-github-pages@v1
        if: success()
        with:
          target_branch: gh-pages
          build_dir: target/docs/html
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
